
service: project_6_jade_on_wheels


image: project_6_jade_on_wheels


servers:
  web:
    - 192.168.0.1
  
  
  
  













registry:
  
  server: localhost:5555

  
  

  
  
  


env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    
    
    SOLID_QUEUE_IN_PUMA: true

    
    

    
    

    
    
    

    
    



aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"



volumes:
  - "project_6_jade_on_wheels_storage:/rails/storage"




asset_path: /rails/public/assets


builder:
  arch: amd64

  
  
  
  
  
  
  
  
  




























